name: Tests

on:
  push:
    branches:
      - master
      - v4
  pull_request:
    branches: [ master ]
    types: [opened, synchronize]

jobs:
            
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version: '16'
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn run lint

  test:
    needs: [ lint ]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: yarn 
    - run: yarn test